### ISSUE TITLE
Filenames can exceed filesystem max character limit

### ISSUE THREAD

**Issue by Cr8zyIvan** [igorlogius/save-website-as-image#1]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to defined automatic custom file naming. 

I must say I very much appreciate the details with which the file names are generated. The type of preciseness I normally seek and praise. In my particular circumstance however, the file names generated become very long, and when they are moved to folders which have a considerable parent tree length, Windows becomes incapable of managing these files, as the full path name exceeds its limit.

**Describe the solution you'd like**
I would add an option under the already "Max Page Height" option, with syntax resembling that of ShareX's File naming settings (or perhaps a system that is even better than that one).
https://getsharex.com/

**Describe alternatives you've considered**
In my case, because I sometimes generate numerous website images (for references and whatnot), the solution I've adopted is placing all the newly downloaded images in a folder, and renaming them in batches with the "Advanced Renamer" software. It gets the job done, but with extra steps.
https://www.advancedrenamer.com/

**Additional context**

**Comment by igorlogius** [comment]
> In my particular circumstance however, the file names generated become very long, and when they are moved to folders which have a considerable parent tree length, Windows becomes incapable of managing these files, as the full path name exceeds its limit.

Well, that sounds like a bug ... i'll have to look into. 

> Syntax resembling that of ShareX's File naming settings 

That sounds like a feature request. 

I might have to split this issue into two.

**Comment by Cr8zyIvan** [comment]
I wouldn't call the first "item" a "but" per se, not pertaining to the Add-On at least. It's a Windows behaviour I have encountered many times before.

The second "item" is in fact a feature request which, in my own verbage I called "Enhancement Suggestion".

Cheers!

**Comment by igorlogius** [comment]
Well, i can at least try to truncate the filename  if it exceeds a certain number of characters ... even if that number might not always be the absolute max.

**Comment by igorlogius** [comment]
This should help with the filename issue
